name: "Build and Deploy"
on: [push]
jobs:
  docker-build-publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Docker login
        run: echo ${{ GITHUB_TOKEN }} | docker login docker.pkg.github.com --username yomanz --password-stdin
      - name: Use actions/checkout@v1
        uses: actions/checkout@v1
      - name: Docker build
        run: docker build -t docker.pkg.github.com/widgetbot-io/embed:latest .
      - name: Docker push tag latest
        run: docker push docker.pkg.github.com/widgetbot-io/embed:latest
