name: "Build and Deploy"
on:
  push:
    branches:
      - master
jobs:
  docker-build-publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Submodules
        run: git submodule update --init --recursive --remote
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Build
        run: yarn && yarn build
      - name: Docker login
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com --username yomanz --password-stdin
      - name: Docker build
        run: docker build -t docker.pkg.github.com/widgetbot-io/embed/master:latest .
      - name: Docker push tag latest
        run: docker push docker.pkg.github.com/widgetbot-io/embed/master:latest
